// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for connections to Bitbucket Cloud.
public struct BitbucketCloudConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Bitbucket Cloud Workspace ID to be connected to Google Cloud
  /// Platform.
  public var workspace: Swift.String = Swift.String()

  /// Required. SecretManager resource containing the webhook secret used to
  /// verify webhook events, formatted as `projects/*/secrets/*/versions/*`.
  public var webhookSecretSecretVersion: Swift.String = Swift.String()

  /// Required. An access token with the `repository` access. It can be either a
  /// workspace, project or repository access token. It's recommended to use a
  /// system account to generate the credentials.
  public var readAuthorizerCredential: UserCredential? = nil

  /// Required. An access token with the `webhook`, `repository`,
  /// `repository:admin` and `pullrequest` scope access. It can be either a
  /// workspace, project or repository access token. It's recommended to use a
  /// system account to generate these credentials.
  public var authorizerCredential: UserCredential? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BitbucketCloudConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BitbucketCloudConfig().with { $0.workspace = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let workspace = CodingKeys(stringValue: "workspace")
    static let webhookSecretSecretVersion = CodingKeys(stringValue: "webhookSecretSecretVersion")
    static let readAuthorizerCredential = CodingKeys(stringValue: "readAuthorizerCredential")
    static let authorizerCredential = CodingKeys(stringValue: "authorizerCredential")

    static let _knownKeys: Set<Swift.String> = [
      "workspace",
      "webhookSecretSecretVersion",
      "readAuthorizerCredential",
      "authorizerCredential",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workspace) {
      self.workspace = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .webhookSecretSecretVersion)
    {
      self.webhookSecretSecretVersion = value
    }
    self.readAuthorizerCredential = try container.decodeIfPresent(
      UserCredential.self, forKey: .readAuthorizerCredential)
    self.authorizerCredential = try container.decodeIfPresent(
      UserCredential.self, forKey: .authorizerCredential)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.workspace, forKey: .workspace)
    try container.encode(self.webhookSecretSecretVersion, forKey: .webhookSecretSecretVersion)
    try container.encodeIfPresent(self.readAuthorizerCredential, forKey: .readAuthorizerCredential)
    try container.encodeIfPresent(self.authorizerCredential, forKey: .authorizerCredential)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.BitbucketCloudConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
