// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A connection to a SCM like GitHub, GitHub Enterprise, Bitbucket Data Center,
/// Bitbucket Cloud or GitLab.
public struct Connection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the connection, in the format
  /// `projects/{project}/locations/{location}/connections/{connection_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned timestamp for when the connection was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Server assigned timestamp for when the connection was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Installation state of the Connection.
  public var installationState: InstallationState? = nil

  /// If disabled is set to true, functionality is disabled for this connection.
  /// Repository based API methods and webhooks processing for repositories in
  /// this connection will be disabled.
  public var disabled: Swift.Bool = Swift.Bool()

  /// Output only. Set to true when the connection is being set up or updated in
  /// the background.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Allows clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Configuration for the connection depending on the type of provider.
  public var connectionConfig: OneOf_ConnectionConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Connection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let githubConfig = CodingKeys(stringValue: "githubConfig")
    static let githubEnterpriseConfig = CodingKeys(stringValue: "githubEnterpriseConfig")
    static let gitlabConfig = CodingKeys(stringValue: "gitlabConfig")
    static let bitbucketDataCenterConfig = CodingKeys(stringValue: "bitbucketDataCenterConfig")
    static let bitbucketCloudConfig = CodingKeys(stringValue: "bitbucketCloudConfig")
    static let installationState = CodingKeys(stringValue: "installationState")
    static let disabled = CodingKeys(stringValue: "disabled")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "githubConfig",
      "githubEnterpriseConfig",
      "gitlabConfig",
      "bitbucketDataCenterConfig",
      "bitbucketCloudConfig",
      "installationState",
      "disabled",
      "reconciling",
      "annotations",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.installationState = try container.decodeIfPresent(
      InstallationState.self, forKey: .installationState)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
      self.disabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }

    var connectionConfig: OneOf_ConnectionConfig? = nil
    let connectionConfigCheckAndSet = {
      if connectionConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connectionConfig'"))
      }
      connectionConfig = $0
    }
    if let githubConfig = try container.decodeIfPresent(GitHubConfig?.self, forKey: .githubConfig) {
      try connectionConfigCheckAndSet(.githubConfig(githubConfig))
    }
    if let githubEnterpriseConfig = try container.decodeIfPresent(
      GitHubEnterpriseConfig?.self, forKey: .githubEnterpriseConfig)
    {
      try connectionConfigCheckAndSet(.githubEnterpriseConfig(githubEnterpriseConfig))
    }
    if let gitlabConfig = try container.decodeIfPresent(GitLabConfig?.self, forKey: .gitlabConfig) {
      try connectionConfigCheckAndSet(.gitlabConfig(gitlabConfig))
    }
    if let bitbucketDataCenterConfig = try container.decodeIfPresent(
      BitbucketDataCenterConfig?.self, forKey: .bitbucketDataCenterConfig)
    {
      try connectionConfigCheckAndSet(.bitbucketDataCenterConfig(bitbucketDataCenterConfig))
    }
    if let bitbucketCloudConfig = try container.decodeIfPresent(
      BitbucketCloudConfig?.self, forKey: .bitbucketCloudConfig)
    {
      try connectionConfigCheckAndSet(.bitbucketCloudConfig(bitbucketCloudConfig))
    }
    self.connectionConfig = connectionConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.installationState, forKey: .installationState)
    try container.encode(self.disabled, forKey: .disabled)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.connectionConfig {
      switch choice {
      case .githubConfig(let value):
        try container.encode(value, forKey: .githubConfig)
      case .githubEnterpriseConfig(let value):
        try container.encode(value, forKey: .githubEnterpriseConfig)
      case .gitlabConfig(let value):
        try container.encode(value, forKey: .gitlabConfig)
      case .bitbucketDataCenterConfig(let value):
        try container.encode(value, forKey: .bitbucketDataCenterConfig)
      case .bitbucketCloudConfig(let value):
        try container.encode(value, forKey: .bitbucketCloudConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for the connection depending on the type of provider.
  public enum OneOf_ConnectionConfig: Codable, Equatable, Sendable {
    /// Configuration for connections to github.com.
    indirect case githubConfig(GitHubConfig?)
    /// Configuration for connections to an instance of GitHub Enterprise.
    indirect case githubEnterpriseConfig(GitHubEnterpriseConfig?)
    /// Configuration for connections to gitlab.com or an instance of GitLab
    /// Enterprise.
    indirect case gitlabConfig(GitLabConfig?)
    /// Configuration for connections to Bitbucket Data Center.
    indirect case bitbucketDataCenterConfig(BitbucketDataCenterConfig?)
    /// Configuration for connections to Bitbucket Cloud.
    indirect case bitbucketCloudConfig(BitbucketCloudConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.Connection"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
