// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for connections to an instance of GitHub Enterprise.
public struct GitHubEnterpriseConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The URI of the GitHub Enterprise host this connection is for.
  public var hostUri: Swift.String = Swift.String()

  /// Required. API Key used for authentication of webhook events.
  public var apiKey: Swift.String = Swift.String()

  /// Id of the GitHub App created from the manifest.
  public var appId: Swift.Int64 = Swift.Int64()

  /// The URL-friendly name of the GitHub App.
  public var appSlug: Swift.String = Swift.String()

  /// SecretManager resource containing the private key of the GitHub App,
  /// formatted as `projects/*/secrets/*/versions/*`.
  public var privateKeySecretVersion: Swift.String = Swift.String()

  /// SecretManager resource containing the webhook secret of the GitHub App,
  /// formatted as `projects/*/secrets/*/versions/*`.
  public var webhookSecretSecretVersion: Swift.String = Swift.String()

  /// ID of the installation of the GitHub App.
  public var appInstallationId: Swift.Int64 = Swift.Int64()

  /// Configuration for using Service Directory to privately connect to a GitHub
  /// Enterprise server. This should only be set if the GitHub Enterprise server
  /// is hosted on-premises and not reachable by public internet. If this field
  /// is left empty, calls to the GitHub Enterprise server will be made over the
  /// public internet.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// SSL certificate to use for requests to GitHub Enterprise.
  public var sslCa: Swift.String = Swift.String()

  /// Output only. GitHub Enterprise version installed at the host_uri.
  public var serverVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitHubEnterpriseConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitHubEnterpriseConfig().with { $0.hostUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hostUri = CodingKeys(stringValue: "hostUri")
    static let apiKey = CodingKeys(stringValue: "apiKey")
    static let appId = CodingKeys(stringValue: "appId")
    static let appSlug = CodingKeys(stringValue: "appSlug")
    static let privateKeySecretVersion = CodingKeys(stringValue: "privateKeySecretVersion")
    static let webhookSecretSecretVersion = CodingKeys(stringValue: "webhookSecretSecretVersion")
    static let appInstallationId = CodingKeys(stringValue: "appInstallationId")
    static let serviceDirectoryConfig = CodingKeys(stringValue: "serviceDirectoryConfig")
    static let sslCa = CodingKeys(stringValue: "sslCa")
    static let serverVersion = CodingKeys(stringValue: "serverVersion")

    static let _knownKeys: Set<Swift.String> = [
      "hostUri",
      "apiKey",
      "appId",
      "appSlug",
      "privateKeySecretVersion",
      "webhookSecretSecretVersion",
      "appInstallationId",
      "serviceDirectoryConfig",
      "sslCa",
      "serverVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostUri) {
      self.hostUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiKey) {
      self.apiKey = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .appId) {
      self.appId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appSlug) {
      self.appSlug = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .privateKeySecretVersion)
    {
      self.privateKeySecretVersion = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .webhookSecretSecretVersion)
    {
      self.webhookSecretSecretVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .appInstallationId) {
      self.appInstallationId = value
    }
    self.serviceDirectoryConfig = try container.decodeIfPresent(
      ServiceDirectoryConfig.self, forKey: .serviceDirectoryConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sslCa) {
      self.sslCa = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serverVersion) {
      self.serverVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostUri, forKey: .hostUri)
    try container.encode(self.apiKey, forKey: .apiKey)
    try container.encode(self.appId, forKey: .appId)
    try container.encode(self.appSlug, forKey: .appSlug)
    try container.encode(self.privateKeySecretVersion, forKey: .privateKeySecretVersion)
    try container.encode(self.webhookSecretSecretVersion, forKey: .webhookSecretSecretVersion)
    try container.encode(self.appInstallationId, forKey: .appInstallationId)
    try container.encodeIfPresent(self.serviceDirectoryConfig, forKey: .serviceDirectoryConfig)
    try container.encode(self.sslCa, forKey: .sslCa)
    try container.encode(self.serverVersion, forKey: .serverVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.GitHubEnterpriseConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
