// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for connections to gitlab.com or an instance of GitLab
/// Enterprise.
public struct GitLabConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The URI of the GitLab Enterprise host this connection is for.
  /// If not specified, the default value is https://gitlab.com.
  public var hostUri: Swift.String = Swift.String()

  /// Required. Immutable. SecretManager resource containing the webhook secret
  /// of a GitLab Enterprise project, formatted as
  /// `projects/*/secrets/*/versions/*`.
  public var webhookSecretSecretVersion: Swift.String = Swift.String()

  /// Required. A GitLab personal access token with the minimum `read_api` scope
  /// access.
  public var readAuthorizerCredential: UserCredential? = nil

  /// Required. A GitLab personal access token with the `api` scope access.
  public var authorizerCredential: UserCredential? = nil

  /// Configuration for using Service Directory to privately connect to a GitLab
  /// Enterprise server. This should only be set if the GitLab Enterprise server
  /// is hosted on-premises and not reachable by public internet. If this field
  /// is left empty, calls to the GitLab Enterprise server will be made over the
  /// public internet.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// SSL certificate to use for requests to GitLab Enterprise.
  public var sslCa: Swift.String = Swift.String()

  /// Output only. Version of the GitLab Enterprise server running on the
  /// `host_uri`.
  public var serverVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitLabConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitLabConfig().with { $0.hostUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hostUri = CodingKeys(stringValue: "hostUri")
    static let webhookSecretSecretVersion = CodingKeys(stringValue: "webhookSecretSecretVersion")
    static let readAuthorizerCredential = CodingKeys(stringValue: "readAuthorizerCredential")
    static let authorizerCredential = CodingKeys(stringValue: "authorizerCredential")
    static let serviceDirectoryConfig = CodingKeys(stringValue: "serviceDirectoryConfig")
    static let sslCa = CodingKeys(stringValue: "sslCa")
    static let serverVersion = CodingKeys(stringValue: "serverVersion")

    static let _knownKeys: Set<Swift.String> = [
      "hostUri",
      "webhookSecretSecretVersion",
      "readAuthorizerCredential",
      "authorizerCredential",
      "serviceDirectoryConfig",
      "sslCa",
      "serverVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostUri) {
      self.hostUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .webhookSecretSecretVersion)
    {
      self.webhookSecretSecretVersion = value
    }
    self.readAuthorizerCredential = try container.decodeIfPresent(
      UserCredential.self, forKey: .readAuthorizerCredential)
    self.authorizerCredential = try container.decodeIfPresent(
      UserCredential.self, forKey: .authorizerCredential)
    self.serviceDirectoryConfig = try container.decodeIfPresent(
      ServiceDirectoryConfig.self, forKey: .serviceDirectoryConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sslCa) {
      self.sslCa = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serverVersion) {
      self.serverVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostUri, forKey: .hostUri)
    try container.encode(self.webhookSecretSecretVersion, forKey: .webhookSecretSecretVersion)
    try container.encodeIfPresent(self.readAuthorizerCredential, forKey: .readAuthorizerCredential)
    try container.encodeIfPresent(self.authorizerCredential, forKey: .authorizerCredential)
    try container.encodeIfPresent(self.serviceDirectoryConfig, forKey: .serviceDirectoryConfig)
    try container.encode(self.sslCa, forKey: .sslCa)
    try container.encode(self.serverVersion, forKey: .serverVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.GitLabConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
