// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes stage and necessary actions to be taken by the
/// user to complete the installation. Used for GitHub and GitHub Enterprise
/// based connections.
public struct InstallationState: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Current step of the installation process.
  public var stage: InstallationState.Stage = InstallationState.Stage()

  /// Output only. Message of what the user should do next to continue the
  /// installation. Empty string if the installation is already complete.
  public var message: Swift.String = Swift.String()

  /// Output only. Link to follow for next action. Empty string if the
  /// installation is already complete.
  public var actionUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InstallationState`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InstallationState().with { $0.stage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let stage = CodingKeys(stringValue: "stage")
    static let message = CodingKeys(stringValue: "message")
    static let actionUri = CodingKeys(stringValue: "actionUri")

    static let _knownKeys: Set<Swift.String> = [
      "stage",
      "message",
      "actionUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(InstallationState.Stage.self, forKey: .stage) {
      self.stage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .actionUri) {
      self.actionUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.stage, forKey: .stage)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.actionUri, forKey: .actionUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stage of the installation process.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Stage: Codable, Equatable, Hashable, Sendable {
    /// No stage specified.
    case unspecified
    /// Only for GitHub Enterprise. An App creation has been requested.
    /// The user needs to confirm the creation in their GitHub enterprise host.
    case pendingCreateApp
    /// User needs to authorize the GitHub (or Enterprise) App via OAuth.
    case pendingUserOauth
    /// User needs to follow the link to install the GitHub (or Enterprise) App.
    case pendingInstallApp
    /// Installation process has been completed.
    case complete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pendingCreateApp: return 1
      case .pendingUserOauth: return 2
      case .pendingInstallApp: return 3
      case .complete: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STAGE_UNSPECIFIED"
      case .pendingCreateApp: return "PENDING_CREATE_APP"
      case .pendingUserOauth: return "PENDING_USER_OAUTH"
      case .pendingInstallApp: return "PENDING_INSTALL_APP"
      case .complete: return "COMPLETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Stage/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STAGE_UNSPECIFIED": self = .unspecified
      case "PENDING_CREATE_APP": self = .pendingCreateApp
      case "PENDING_USER_OAUTH": self = .pendingUserOauth
      case "PENDING_INSTALL_APP": self = .pendingInstallApp
      case "COMPLETE": self = .complete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Stage/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pendingCreateApp
      case 2: self = .pendingUserOauth
      case 3: self = .pendingInstallApp
      case 10: self = .complete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STAGE_UNSPECIFIED")
      case .pendingCreateApp: return try container.encode("PENDING_CREATE_APP")
      case .pendingUserOauth: return try container.encode("PENDING_USER_OAUTH")
      case .pendingInstallApp: return try container.encode("PENDING_INSTALL_APP")
      case .complete: return try container.encode("COMPLETE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.InstallationState"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
