// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages connections to source code repositories.
///
/// @Snippet(path: "RepositoryManagerQuickstart")
public final class RepositoryManagerClient: Clients.RepositoryManagerProtocol, Sendable {
  let inner: any Clients.RepositoryManagerStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `RepositoryManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.RepositoryManagerStub = try Clients.RepositoryManagerTransport(options)
    inner = Clients.RepositoryManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RepositoryManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a Connection.
  ///
  /// @Snippet(path: "RepositoryManager_CreateConnection")
  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnection(request: request, options: options)
  }

  /// Creates a Connection.
  ///
  /// @Snippet(path: "RepositoryManager_CreateConnection")
  public func createConnectionPollingUntilDone(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Connection>.State
      in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.createConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details of a single connection.
  ///
  /// @Snippet(path: "RepositoryManager_GetConnection")
  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.Connection {
    try await self.inner.getConnection(request: request, options: options)
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "RepositoryManager_ListConnections")
  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.ListConnectionsResponse {
    try await self.inner.listConnections(request: request, options: options)
  }

  /// Updates a single connection.
  ///
  /// @Snippet(path: "RepositoryManager_UpdateConnection")
  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnection(request: request, options: options)
  }

  /// Updates a single connection.
  ///
  /// @Snippet(path: "RepositoryManager_UpdateConnection")
  public func updateConnectionPollingUntilDone(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Connection>.State
      in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.updateConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single connection.
  ///
  /// @Snippet(path: "RepositoryManager_DeleteConnection")
  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnection(request: request, options: options)
  }

  /// Deletes a single connection.
  ///
  /// @Snippet(path: "RepositoryManager_DeleteConnection")
  public func deleteConnectionPollingUntilDone(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a Repository.
  ///
  /// @Snippet(path: "RepositoryManager_CreateRepository")
  public func createRepository(
    request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createRepository(request: request, options: options)
  }

  /// Creates a Repository.
  ///
  /// @Snippet(path: "RepositoryManager_CreateRepository")
  public func createRepositoryPollingUntilDone(
    request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Repository> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Repository>.State
      in
      return try op._extractStatus(Repository.self)
    }
    let rawOp = try await self.createRepository(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Repository>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates multiple repositories inside a connection.
  ///
  /// @Snippet(path: "RepositoryManager_BatchCreateRepositories")
  public func batchCreateRepositories(
    request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchCreateRepositories(request: request, options: options)
  }

  /// Creates multiple repositories inside a connection.
  ///
  /// @Snippet(path: "RepositoryManager_BatchCreateRepositories")
  public func batchCreateRepositoriesPollingUntilDone(
    request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchCreateRepositoriesResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<BatchCreateRepositoriesResponse>.State in
      return try op._extractStatus(BatchCreateRepositoriesResponse.self)
    }
    let rawOp = try await self.batchCreateRepositories(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchCreateRepositoriesResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details of a single repository.
  ///
  /// @Snippet(path: "RepositoryManager_GetRepository")
  public func getRepository(
    request: GetRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.Repository {
    try await self.inner.getRepository(request: request, options: options)
  }

  /// Lists Repositories in a given connection.
  ///
  /// @Snippet(path: "RepositoryManager_ListRepositories")
  public func listRepositories(
    request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.ListRepositoriesResponse {
    try await self.inner.listRepositories(request: request, options: options)
  }

  /// Deletes a single repository.
  ///
  /// @Snippet(path: "RepositoryManager_DeleteRepository")
  public func deleteRepository(
    request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRepository(request: request, options: options)
  }

  /// Deletes a single repository.
  ///
  /// @Snippet(path: "RepositoryManager_DeleteRepository")
  public func deleteRepositoryPollingUntilDone(
    request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteRepository(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Fetches read/write token of a given repository.
  ///
  /// @Snippet(path: "RepositoryManager_FetchReadWriteToken")
  public func fetchReadWriteToken(
    request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchReadWriteTokenResponse {
    try await self.inner.fetchReadWriteToken(request: request, options: options)
  }

  /// Fetches read token of a given repository.
  ///
  /// @Snippet(path: "RepositoryManager_FetchReadToken")
  public func fetchReadToken(
    request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchReadTokenResponse {
    try await self.inner.fetchReadToken(request: request, options: options)
  }

  /// FetchLinkableRepositories get repositories from SCM that are
  /// accessible and could be added to the connection.
  ///
  /// @Snippet(path: "RepositoryManager_FetchLinkableRepositories")
  public func fetchLinkableRepositories(
    request: FetchLinkableRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchLinkableRepositoriesResponse {
    try await self.inner.fetchLinkableRepositories(request: request, options: options)
  }

  /// Fetch the list of branches or tags for a given repository.
  ///
  /// @Snippet(path: "RepositoryManager_FetchGitRefs")
  public func fetchGitRefs(
    request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchGitRefsResponse {
    try await self.inner.fetchGitRefs(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "RepositoryManager_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "RepositoryManager_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "RepositoryManager_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RepositoryManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "RepositoryManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RepositoryManagerClient`.
  ///
  /// To mock `RepositoryManagerClient` change your functions to receive
  /// `some RepositoryManagerProtocol` or `any RepositoryManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RepositoryManagerProtocol: Sendable {
    /// See `RepositoryManagerClient.createConnection`.
    func createConnection(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.createConnection`.
    func createConnectionPollingUntilDone(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `RepositoryManagerClient.getConnection`.
    func getConnection(
      request: GetConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.Connection

    /// See `RepositoryManagerClient.listConnections`.
    func listConnections(
      request: ListConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.ListConnectionsResponse

    /// See `RepositoryManagerClient.updateConnection`.
    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.updateConnection`.
    func updateConnectionPollingUntilDone(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `RepositoryManagerClient.deleteConnection`.
    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.deleteConnection`.
    func deleteConnectionPollingUntilDone(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `RepositoryManagerClient.createRepository`.
    func createRepository(
      request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.createRepository`.
    func createRepositoryPollingUntilDone(
      request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Repository>

    /// See `RepositoryManagerClient.batchCreateRepositories`.
    func batchCreateRepositories(
      request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.batchCreateRepositories`.
    func batchCreateRepositoriesPollingUntilDone(
      request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<BatchCreateRepositoriesResponse>

    /// See `RepositoryManagerClient.getRepository`.
    func getRepository(
      request: GetRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.Repository

    /// See `RepositoryManagerClient.listRepositories`.
    func listRepositories(
      request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.ListRepositoriesResponse

    /// See `RepositoryManagerClient.deleteRepository`.
    func deleteRepository(
      request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `RepositoryManagerClient.deleteRepository`.
    func deleteRepositoryPollingUntilDone(
      request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `RepositoryManagerClient.fetchReadWriteToken`.
    func fetchReadWriteToken(
      request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.FetchReadWriteTokenResponse

    /// See `RepositoryManagerClient.fetchReadToken`.
    func fetchReadToken(
      request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.FetchReadTokenResponse

    /// See `RepositoryManagerClient.fetchLinkableRepositories`.
    func fetchLinkableRepositories(
      request: FetchLinkableRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.FetchLinkableRepositoriesResponse

    /// See `RepositoryManagerClient.fetchGitRefs`.
    func fetchGitRefs(
      request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBuildV2.FetchGitRefsResponse

    /// See `RepositoryManagerClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `RepositoryManagerClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `RepositoryManagerClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `RepositoryManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.RepositoryManagerProtocol {
  public func createConnection(request: CreateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnection(request: request, options: .init())
  }

  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConnectionPollingUntilDone(request: CreateConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<Connection>
  {
    try await self.createConnectionPollingUntilDone(request: request, options: .init())
  }

  public func createConnectionPollingUntilDone(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnectionPollingUntilDone(
    parent: Swift.String,
    connection: Connection?,
    connectionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let request = CreateConnectionRequest().with {
      $0.parent = parent
      $0.connection = connection
      $0.connectionId = connectionId
    }
    return try await self.createConnectionPollingUntilDone(request: request)
  }

  public func getConnection(request: GetConnectionRequest) async throws
    -> GoogleCloudBuildV2.Connection
  {
    try await self.getConnection(request: request, options: .init())
  }

  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.Connection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudBuildV2.Connection {
    let request = GetConnectionRequest().with {
      $0.name = name
    }
    return try await self.getConnection(request: request)
  }

  public func listConnections(request: ListConnectionsRequest) async throws
    -> GoogleCloudBuildV2.ListConnectionsResponse
  {
    try await self.listConnections(request: request, options: .init())
  }

  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.ListConnectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnectionsByItems(
    request: ListConnectionsRequest
  ) -> any AsyncSequence<Connection, Swift.Error> & Sendable {
    self.listConnectionsByItems(request: request, options: .init())
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "RepositoryManager_ListConnections")
  public func listConnectionsByItems(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Connection, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudBuildV2.ListConnectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConnections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Connection, Swift.Error> & Sendable {
    let request = ListConnectionsRequest().with {
      $0.parent = parent
    }
    return self.listConnectionsByItems(request: request)
  }

  public func updateConnection(request: UpdateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnection(request: request, options: .init())
  }

  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConnectionPollingUntilDone(request: UpdateConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<Connection>
  {
    try await self.updateConnectionPollingUntilDone(request: request, options: .init())
  }

  public func updateConnectionPollingUntilDone(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConnectionPollingUntilDone(
    connection: Connection?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let request = UpdateConnectionRequest().with {
      $0.connection = connection
      $0.updateMask = updateMask
    }
    return try await self.updateConnectionPollingUntilDone(request: request)
  }

  public func deleteConnection(request: DeleteConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnection(request: request, options: .init())
  }

  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConnectionPollingUntilDone(request: DeleteConnectionRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConnectionPollingUntilDone(request: request, options: .init())
  }

  public func deleteConnectionPollingUntilDone(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectionPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteConnectionRequest().with {
      $0.name = name
    }
    return try await self.deleteConnectionPollingUntilDone(request: request)
  }

  public func createRepository(request: CreateRepositoryRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createRepository(request: request, options: .init())
  }

  public func createRepository(
    request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createRepositoryPollingUntilDone(request: CreateRepositoryRequest) async throws
    -> any GoogleGax.PollableOperation<Repository>
  {
    try await self.createRepositoryPollingUntilDone(request: request, options: .init())
  }

  public func createRepositoryPollingUntilDone(
    request: CreateRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Repository> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Repository>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createRepositoryPollingUntilDone(
    parent: Swift.String,
    repository: Repository?,
    repositoryId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Repository> {
    let request = CreateRepositoryRequest().with {
      $0.parent = parent
      $0.repository = repository
      $0.repositoryId = repositoryId
    }
    return try await self.createRepositoryPollingUntilDone(request: request)
  }

  public func batchCreateRepositories(request: BatchCreateRepositoriesRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchCreateRepositories(request: request, options: .init())
  }

  public func batchCreateRepositories(
    request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func batchCreateRepositoriesPollingUntilDone(request: BatchCreateRepositoriesRequest)
    async throws -> any GoogleGax.PollableOperation<BatchCreateRepositoriesResponse>
  {
    try await self.batchCreateRepositoriesPollingUntilDone(request: request, options: .init())
  }

  public func batchCreateRepositoriesPollingUntilDone(
    request: BatchCreateRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<BatchCreateRepositoriesResponse> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<BatchCreateRepositoriesResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchCreateRepositoriesPollingUntilDone(
    parent: Swift.String,
    requests: [CreateRepositoryRequest],
  ) async throws -> any GoogleGax.PollableOperation<BatchCreateRepositoriesResponse> {
    let request = BatchCreateRepositoriesRequest().with {
      $0.parent = parent
      $0.requests = requests
    }
    return try await self.batchCreateRepositoriesPollingUntilDone(request: request)
  }

  public func getRepository(request: GetRepositoryRequest) async throws
    -> GoogleCloudBuildV2.Repository
  {
    try await self.getRepository(request: request, options: .init())
  }

  public func getRepository(
    request: GetRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.Repository {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRepository(
    name: Swift.String,
  ) async throws -> GoogleCloudBuildV2.Repository {
    let request = GetRepositoryRequest().with {
      $0.name = name
    }
    return try await self.getRepository(request: request)
  }

  public func listRepositories(request: ListRepositoriesRequest) async throws
    -> GoogleCloudBuildV2.ListRepositoriesResponse
  {
    try await self.listRepositories(request: request, options: .init())
  }

  public func listRepositories(
    request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.ListRepositoriesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRepositoriesByItems(
    request: ListRepositoriesRequest
  ) -> any AsyncSequence<Repository, Swift.Error> & Sendable {
    self.listRepositoriesByItems(request: request, options: .init())
  }

  /// Lists Repositories in a given connection.
  ///
  /// @Snippet(path: "RepositoryManager_ListRepositories")
  public func listRepositoriesByItems(
    request: ListRepositoriesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Repository, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudBuildV2.ListRepositoriesResponse in
      var request = request
      request.pageToken = token
      return try await self.listRepositories(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRepositoriesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Repository, Swift.Error> & Sendable {
    let request = ListRepositoriesRequest().with {
      $0.parent = parent
    }
    return self.listRepositoriesByItems(request: request)
  }

  public func deleteRepository(request: DeleteRepositoryRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteRepository(request: request, options: .init())
  }

  public func deleteRepository(
    request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteRepositoryPollingUntilDone(request: DeleteRepositoryRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteRepositoryPollingUntilDone(request: request, options: .init())
  }

  public func deleteRepositoryPollingUntilDone(
    request: DeleteRepositoryRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRepositoryPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteRepositoryRequest().with {
      $0.name = name
    }
    return try await self.deleteRepositoryPollingUntilDone(request: request)
  }

  public func fetchReadWriteToken(request: FetchReadWriteTokenRequest) async throws
    -> GoogleCloudBuildV2.FetchReadWriteTokenResponse
  {
    try await self.fetchReadWriteToken(request: request, options: .init())
  }

  public func fetchReadWriteToken(
    request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchReadWriteTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchReadWriteToken(
    repository: Swift.String,
  ) async throws -> GoogleCloudBuildV2.FetchReadWriteTokenResponse {
    let request = FetchReadWriteTokenRequest().with {
      $0.repository = repository
    }
    return try await self.fetchReadWriteToken(request: request)
  }

  public func fetchReadToken(request: FetchReadTokenRequest) async throws
    -> GoogleCloudBuildV2.FetchReadTokenResponse
  {
    try await self.fetchReadToken(request: request, options: .init())
  }

  public func fetchReadToken(
    request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchReadTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchReadToken(
    repository: Swift.String,
  ) async throws -> GoogleCloudBuildV2.FetchReadTokenResponse {
    let request = FetchReadTokenRequest().with {
      $0.repository = repository
    }
    return try await self.fetchReadToken(request: request)
  }

  public func fetchLinkableRepositories(request: FetchLinkableRepositoriesRequest) async throws
    -> GoogleCloudBuildV2.FetchLinkableRepositoriesResponse
  {
    try await self.fetchLinkableRepositories(request: request, options: .init())
  }

  public func fetchLinkableRepositories(
    request: FetchLinkableRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchLinkableRepositoriesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchLinkableRepositoriesByItems(
    request: FetchLinkableRepositoriesRequest
  ) -> any AsyncSequence<Repository, Swift.Error> & Sendable {
    self.fetchLinkableRepositoriesByItems(request: request, options: .init())
  }

  /// FetchLinkableRepositories get repositories from SCM that are
  /// accessible and could be added to the connection.
  ///
  /// @Snippet(path: "RepositoryManager_FetchLinkableRepositories")
  public func fetchLinkableRepositoriesByItems(
    request: FetchLinkableRepositoriesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Repository, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBuildV2.FetchLinkableRepositoriesResponse in
      var request = request
      request.pageToken = token
      return try await self.fetchLinkableRepositories(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func fetchGitRefs(request: FetchGitRefsRequest) async throws
    -> GoogleCloudBuildV2.FetchGitRefsResponse
  {
    try await self.fetchGitRefs(request: request, options: .init())
  }

  public func fetchGitRefs(
    request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBuildV2.FetchGitRefsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchGitRefs(
    repository: Swift.String,
  ) async throws -> GoogleCloudBuildV2.FetchGitRefsResponse {
    let request = FetchGitRefsRequest().with {
      $0.repository = repository
    }
    return try await self.fetchGitRefs(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
