// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A repository associated to a parent connection.
public struct Repository: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. Resource name of the repository, in the format
  /// `projects/*/locations/*/connections/*/repositories/*`.
  public var name: Swift.String = Swift.String()

  /// Required. Git Clone HTTPS URI.
  public var remoteUri: Swift.String = Swift.String()

  /// Output only. Server assigned timestamp for when the connection was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Server assigned timestamp for when the connection was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Allows clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. External ID of the webhook created for the repository.
  public var webhookId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Repository`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Repository().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let remoteUri = CodingKeys(stringValue: "remoteUri")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let etag = CodingKeys(stringValue: "etag")
    static let webhookId = CodingKeys(stringValue: "webhookId")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "remoteUri",
      "createTime",
      "updateTime",
      "annotations",
      "etag",
      "webhookId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remoteUri) {
      self.remoteUri = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .webhookId) {
      self.webhookId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.remoteUri, forKey: .remoteUri)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.webhookId, forKey: .webhookId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudbuild.v2.Repository"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
